"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Recommendation = { id: number; name: string; role: string; company: string | null; photo: string | null; stars: number; comment: string; createdAt: string };

function Stars({ value }: { value: number }) {
  return <span className="recommendation-stars" aria-label={`${value} de 5 estrelas`}>{[1,2,3,4,5].map(n => <i className={n <= value ? "filled" : ""} key={n}>★</i>)}</span>;
}

async function compactPhoto(file: File) {
  if (!file.type.startsWith("image/")) throw new Error("Escolha um arquivo de imagem.");
  const source = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
  const image = await new Promise<HTMLImageElement>((resolve, reject) => { const img = new Image(); img.onload = () => resolve(img); img.onerror = reject; img.src = source; });
  const canvas = document.createElement("canvas"); canvas.width = 180; canvas.height = 180;
  const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("Não foi possível processar a foto.");
  const side = Math.min(image.naturalWidth, image.naturalHeight); const sx = (image.naturalWidth-side)/2; const sy = (image.naturalHeight-side)/2;
  ctx.drawImage(image,sx,sy,side,side,0,0,180,180);
  return canvas.toDataURL("image/webp",.78);
}

export default function Recommendations() {
  const [items,setItems] = useState<Recommendation[]>([]); const [stats,setStats] = useState({count:0,average:0}); const [open,setOpen] = useState(false); const [stars,setStars] = useState(5); const [photo,setPhoto] = useState(""); const [state,setState] = useState<"idle"|"sending"|"sent"|"error">("idle"); const [message,setMessage] = useState(""); const track=useRef<HTMLDivElement>(null);
  useEffect(()=>{fetch("/api/recommendations").then(r=>r.ok?r.json():Promise.reject()).then(data=>{setItems(data.recommendations||[]);setStats(data.stats||{count:0,average:0})}).catch(()=>{})},[]);
  useEffect(()=>{document.body.style.overflow=open?"hidden":"";const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};addEventListener("keydown",key);return()=>{document.body.style.overflow="";removeEventListener("keydown",key)}},[open]);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setState("sending");setMessage("");const form=new FormData(e.currentTarget);const payload={name:form.get("name"),role:form.get("role"),company:form.get("company"),email:form.get("email"),comment:form.get("comment"),website:form.get("website"),stars,photo};try{const res=await fetch("/api/recommendations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Não foi possível enviar.");setState("sent");setMessage(data.message);e.currentTarget.reset();setPhoto("");setStars(5)}catch(err){setState("error");setMessage(err instanceof Error?err.message:"Não foi possível enviar.")}};
  const displayed = [...items, ...Array.from({length:Math.max(0,3-items.length)},(_,i)=>({id:-(i+1),placeholder:true}))].slice(0,Math.max(3,items.length));
  return <section className="recommendations section" id="recomendacoes"><div className="recommendations-heading"><div><div className="section-label"><span>08</span> REPUTAÇÃO PROFISSIONAL</div><h2>O que dizem sobre<br/><em>meu trabalho.</em></h2></div><div className="recommendations-score"><Stars value={stats.count?Math.round(stats.average):5}/><strong>{stats.count?stats.average.toFixed(1):"—"}</strong><p>{stats.count?`Baseado em ${stats.count} recomendaç${stats.count===1?"ão":"ões"} aprovada${stats.count===1?"":"s"}.`:"As recomendações verificadas aparecerão aqui após aprovação."}</p></div></div><div className="recommendations-toolbar"><p>Relatos de gestores, colegas, clientes e parceiros que acompanharam meu trabalho de perto.</p><div><button onClick={()=>track.current?.scrollBy({left:-420,behavior:"smooth"})} aria-label="Recomendação anterior">←</button><button onClick={()=>track.current?.scrollBy({left:420,behavior:"smooth"})} aria-label="Próxima recomendação">→</button><button className="recommendation-cta" onClick={()=>{setOpen(true);setState("idle");setMessage("")}}>Deixar uma recomendação</button></div></div><div className="recommendations-track" ref={track}>{displayed.map(entry=>"placeholder" in entry?<article className="recommendation-card placeholder" key={entry.id}><span>RECOMENDAÇÃO VERIFICADA</span><h3>Este espaço será ocupado por uma recomendação aprovada.</h3><p>Trabalhou comigo? Compartilhe sua experiência profissional de forma transparente.</p><button onClick={()=>setOpen(true)}>Escrever recomendação →</button></article>:<article className="recommendation-card" key={entry.id}><header><div className="recommendation-person">{entry.photo?<img src={entry.photo} alt=""/>:<span>{entry.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("")}</span>}<div><strong>{entry.name}</strong><small>{entry.role}{entry.company?` · ${entry.company}`:""}</small></div></div><Stars value={entry.stars}/></header><blockquote>“{entry.comment}”</blockquote><footer><span>RECOMENDAÇÃO PROFISSIONAL</span><time dateTime={entry.createdAt}>{new Date(entry.createdAt).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</time></footer></article>)}</div>
  {open&&<div className="recommendation-modal" role="dialog" aria-modal="true" aria-labelledby="recommendation-title" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form onSubmit={submit}><button type="button" className="recommendation-close" onClick={()=>setOpen(false)} aria-label="Fechar">×</button><span>RECOMENDAÇÃO PROFISSIONAL</span><h2 id="recommendation-title">Conte como foi trabalhar comigo.</h2><p>Seu e-mail será usado apenas para validação e nunca ficará público. A recomendação será revisada antes da publicação.</p>{state==="sent"?<div className="recommendation-success"><i>✓</i><h3>Obrigado pela recomendação.</h3><p>{message}</p><button type="button" onClick={()=>setOpen(false)}>Concluir</button></div>:<><div className="recommendation-form-grid"><label>Nome<input name="name" required maxLength={100}/></label><label>Cargo<input name="role" required maxLength={120}/></label><label>Empresa <small>opcional</small><input name="company" maxLength={120}/></label><label>E-mail <small>não será exibido</small><input name="email" type="email" required maxLength={180}/></label></div><label className="photo-field">Foto <small>opcional</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{setPhoto(await compactPhoto(file));setMessage("")}catch(err){setMessage(err instanceof Error?err.message:"Foto inválida.")}}}/>{photo&&<img src={photo} alt="Prévia da foto escolhida"/>}</label><fieldset><legend>Quantidade de estrelas</legend><div className="star-picker">{[1,2,3,4,5].map(n=><button type="button" className={n<=stars?"active":""} onClick={()=>setStars(n)} aria-label={`${n} estrelas`} key={n}>★</button>)}</div></fieldset><label>Comentário<textarea name="comment" required minLength={30} maxLength={1800} rows={6} placeholder="Descreva o contexto, minha atuação e o impacto percebido."/></label><label className="recommendation-hp" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{message&&<p className="recommendation-error">{message}</p>}<button className="recommendation-submit" disabled={state==="sending"}>{state==="sending"?"Enviando…":"Enviar recomendação"}<span>→</span></button></>}</form></div>}</section>;
}
